#!/bin/bash
#----------------------------------------------------
#path and filename
#----------------------------------------------------
source ../path_use
data=$dat_name
index=$2
adex=.dat
adex1=_bak
#echo "my working path=" $my_path
#echo "mc data path=" $mcdat_path
#echo "mc data name=" $data$index$adex
#-----------------------------------------------------
# default file and initial images
#-----------------------------------------------------
echo $index > mdlinput.txt
./disp.out < mdlinput.txt
#cp $flat_path/deflt.dat $default_model
#cp $flat_path/f0.dat $initial_image
#for annealing algorithm
#echo "default model is:" $anneal_file/$index$adex1$adex
cp $anneal_file/$index$adex1$adex $default_model
cp $anneal_file/$index$adex1$adex $initial_image
#-----------------------------------------------------
#create parameter file for rdbin.f
#-----------------------------------------------------
#remove old one
rm -f rdinput.txt
#create new one by add a line for output file name
rdoutfile=$tmp_path/rdbinout.dat
echo $rdoutfile > rdinput.txt
#number of input file
echo 1 >> rdinput.txt
#number of bins
echo $3 >> rdinput.txt
#number of skip
echo $4 >> rdinput.txt
#coarse grain size
echo $5 >> rdinput.txt
#Matsubara frequency or not?
echo 1 >> rdinput.txt
#number of Matsubara frequencies
echo $6 >> rdinput.txt
#print Histogram or not?
echo y >> rdinput.txt
#data is symmetric or not?
echo n >> rdinput.txt
#input file name
if test $1 -eq 0
then
	echo $data$index$adex >> rdinput.txt
else
	echo $swap_dat >> rdinput.txt
fi
#
#run rdbin
./runbin.out < rdinput.txt
#-------------------------------------------------------
#create parameter file for readmc.f
#-------------------------------------------------------
#remove the old one
rm -f mcinput.txt
#input file name, i.e. output file of rdbins.f
echo $rdoutfile > mcinput.txt
#output file name
rdmcoutfile=$tmp_path/mc.dat
echo $rdmcoutfile >> mcinput.txt
#default file name
dftfile=$tmp_path/deflt.dat
echo $dftfile >> mcinput.txt
#eigenvalue file name
eigfile=$tmp_path/eig.dat
echo $eigfile >> mcinput.txt
#value of range, machine precision
echo 1.12E-020 >> mcinput.txt
#type of kernel
echo 5 >> mcinput.txt
#
#run readme
./runmc.out < mcinput.txt
