#!/bin/bash
#
# This bash shell.
# Usage:
# spectra filenumber
#
# SET SOME PATHS (dsigcluster, spectra)
#
source ~/mem_locs

if [ "$1" = "" ] ; then
  echo 'run_spectra file' 
exit
fi

echo 'working on some points'
cat <<EOF> dummy
$1
0,0,3.141592653589793,3.141592653589793,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_G$1
mv Spectra Spectra_G$1
rm -f dummy out
echo 'G done'

cat <<EOF> dummy
$1
3.141592653589793,3.141592653589793,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_M$1
mv Spectra Spectra_M$1
rm -f dummy out
echo 'M done'

cat <<EOF> dummy
$1
0,3.141592653589793,3.141592653589793,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_X$1
mv Spectra Spectra_X$1
rm -f dummy out
echo 'X done'

cat <<EOF> dummy
$1
1.570796326794897,1.570796326794897,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi2pi2_$1
mv Spectra Spectra_pi2pi2_$1
rm -f dummy out
echo 'pi2pi2 done'

cat <<EOF> dummy
$1
0.7853981633974483,0.7853981633974483,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi4pi4_$1
mv Spectra Spectra_pi4pi4_$1
rm -f dummy out
echo 'pi4pi4 done'

cat <<EOF> dummy
$1
0.3926990816987241,0.3926990816987241,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi8pi8_$1
mv Spectra Spectra_pi8pi8_$1
rm -f dummy out
echo 'pi8pi8 done'




cat <<EOF> dummy
$1
1.570796326794897,0,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi20_$1
mv Spectra Spectra_pi20_$1
rm -f dummy out
echo 'pi20 done'


cat <<EOF> dummy
$1
1.570796326794897,3.141592653589793,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi2pi_$1
mv Spectra Spectra_pi2pi_$1
rm -f dummy out
echo 'pi2pi done'

cat <<EOF> dummy
$1
1.570796326794897,0.7853981633974483,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi2pi4_$1
mv Spectra Spectra_pi2pi4_$1
rm -f dummy out
echo 'pi2pi4 done'

cat <<EOF> dummy
$1
1.570796326794897,2.356194490192345,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pi2pi34_$1
mv Spectra Spectra_pi2pi34_$1
rm -f dummy out
echo 'pi2pi34 done'

cat <<EOF> dummy
$1
0,2.356194490192345,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_0pi34_$1
mv Spectra Spectra_0pi34_$1
rm -f dummy out
echo '0pi34 done'

cat <<EOF> dummy
$1
0,0.7853981633974483,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_0pi4_$1
mv Spectra Spectra_0pi4_$1
rm -f dummy out
echo '0pi4 done'


cat <<EOF> dummy
$1
3.141592653589793,0.7853981633974483,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pipi4_$1
mv Spectra Spectra_pipi4_$1
rm -f dummy out
echo 'pipi4 done'

cat <<EOF> dummy
$1
3.141592653589793,2.356194490192345,0,0,0.,1
EOF
$spectra < dummy>out
mv Akw_spectra A_spectra_pipi34_$1
mv Spectra Spectra_pipi34_$1
rm -f dummy out
echo 'pipi34 done'


echo 'B-->A'
cat <<EOF> dummy
$1
1.570796326794897,0,3.141592653589793,1.570796326794897,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_BA$1
mv Spectra Spectra_BA$1
mv MDC MDC_BA$1
rm -f dummy out
echo 'Spectra_BA'$1' done'
cat <<EOF> dummy
$1
1.570796326794897,0,3.141592653589793,1.570796326794897,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_BA$1
$run_falsecolor $1 BA
rm -f dummy out
echo 'False_color_BA'$1' done'



echo 'G-->M'
cat <<EOF> dummy
$1
0,0,3.141592653589793,3.141592653589793,0.1,101
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_GM$1
mv Spectra Spectra_GM$1
mv MDC MDC_GM$1
rm -f dummy out
echo 'Spectra_GM'$1' done'
cat <<EOF> dummy
$1
0,0,3.141592653589793,3.141592653589793,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_GM$1
$run_falsecolor $1 GM
rm -f dummy out
echo 'False_color_GM'$1' done'




echo 'X-->M'
cat <<EOF> dummy
$1
0,3.141592653589793,3.141592653589793,3.141592653589793,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_XM$1
mv Spectra Spectra_XM$1
mv MDC MDC_XM$1
rm -f dummy out
cat <<EOF> dummy
$1
0,3.141592653589793,3.141592653589793,3.141592653589793,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_XM$1
$run_falsecolor $1 XM
rm -f dummy out
echo 'False_color_XM'$1' done'




echo 'G-->X'
cat <<EOF> dummy
$1
0,0,0,3.141592653589793,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_GX$1
mv Spectra Spectra_GX$1
mv MDC MDC_GX$1
echo 'Spectra_GX'$1' done'
rm -f dummy out
cat <<EOF> dummy
$1
0,0,0,3.141592653589793,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_GX$1
$run_falsecolor $1 GX
rm -f dummy out
echo 'False_color_GX'$1' done'


echo 'X-->X'
cat <<EOF> dummy
$1
0,3.141592653589793,3.141592653589793,0,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_XX$1
mv Spectra Spectra_XX$1
mv MDC MDC_XX$1
echo 'Spectra_XX'$1' done'
rm -f dummy out
cat <<EOF> dummy
$1
0,3.141592653589793,3.141592653589793,0,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_XX$1
$run_falsecolor $1 XX
rm -f dummy out
echo 'False_color_XX'$1' done'

echo 'G-->(pi/2,pi)A'
cat <<EOF> dummy
$1
0,0,1.570796326794897,3.141592653589793,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_GA$1
mv Spectra Spectra_GA$1
mv MDC MDC_GA$1
echo 'Spectra_GA'$1' done'
rm -f dummy out
echo 'G-->(pi/2,pi)A'
cat <<EOF> dummy
$1
0,0,1.570796326794897,3.141592653589793,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_GA$1
$run_falsecolor $1 GA
rm -f dummy out
echo 'False_color_GA'$1' done'

echo 'M-->(0,pi/2)B'
cat <<EOF> dummy
$1
3.141592653589793,3.141592653589793,0,1.570796326794897,0.5,15
EOF
$spectra < dummy>out
mv Akw_spectra Akw_spectra_MB$1
mv Spectra Spectra_MB$1
mv MDC MDC_MB$1
rm -f dummy out
echo 'Spectra_MB'$1' done'
cat <<EOF> dummy
$1
3.141592653589793,3.141592653589793,0,1.570796326794897,0.5,101
EOF
$spectra < dummy>out
mv False_color.dat False_color_MB$1
$run_falsecolor $1 MB
rm -f dummy out
echo 'False_color_MB'$1' done'

echo 'working on energy 0 surface'
cat <<EOF> dummy
$1
0.0
300
EOF
$energy_surface <dummy>out
rm -f dummy out
mv energy_surface0.dat energy_surface0_$1
cat <<EOF> dummy
set xlabel "Kx"
set ylabel "Ky"
set size ratio 1
set xrange [0:3.141592653589793]
set yrange [0:3.141592653589793]
#set cbrange[0:3]
set tics out
set pm3d map
splot 'energy_surface0_$1'
set terminal postscript color
set output 'energy_surface0_$1.ps'
replot
EOF
$gnuplot<dummy
rm -f dummy
echo 'energy_surface0 done'


echo 'working on energy 0.025 surface'
cat <<EOF> dummy
$1
0.025
300
EOF
$energy_surface <dummy>out
rm -f dummy out
mv energy_surface0.dat energy_surface0.025_$1
cat <<EOF> dummy
set xlabel "Kx"
set ylabel "Ky"
set size ratio 1
set xrange [0:3.141592653589793]
set yrange [0:3.141592653589793]
#set cbrange[0:3]
set tics out
set pm3d map
splot 'energy_surface0.025_$1'
set terminal postscript color
set output 'energy_surface0.025_$1.ps'
replot
EOF
$gnuplot<dummy
rm -f dummy
echo 'energy_surface0.025 done'

echo 'working on energy -0.025 surface'
cat <<EOF> dummy
$1
-0.025
300
EOF
$energy_surface <dummy>out
rm -f dummy out
mv energy_surface0.dat energy_surfacem0.025_$1
cat <<EOF> dummy
set xlabel "Kx"
set ylabel "Ky"
set size ratio 1
set xrange [0:3.141592653589793]
set yrange [0:3.141592653589793]
#set cbrange[0:3]
set tics out
set pm3d map
splot 'energy_surfacem0.025_$1'
set terminal postscript color
set output 'energy_surfacem0.025_$1.ps'
replot
EOF
$gnuplot<dummy
rm -f dummy
echo 'energy_surfacem0.025 done'

exit
